# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
patch_file = "src/schema.patch"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

import_types = ["diesel::sql_types::*", "postgis_diesel::sql_types::*"]

[migrations_directory]
dir = "/app/migrations"

