version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - grafana-storage:/var/lib/grafana

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  back:
    build:
      context: .
    volumes:
      - .:/app
      - /app/target
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  grafana-storage: {}
