name: main-workflow
on:
  push:
    branches:
      - front-dev
      - back-dev
      - feature/**

jobs:

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-back:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./back
        with:
          workspaces: tests

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests