name: main-workflow
on:
  pull_request_review:
    branches:
      - fron-dev
      - back-dev
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
