name: main-workflow
on:
  push:
    branches:
      - front-dev
      - back-dev
      - feature/**

jobs:

  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      # Setup java env & build android app
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21.x'

      # Setup flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Get flutter dependecnies
      - uses: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
         name: release-apk
         path: build/app/outputs/apk/release/app-release.apk

  build-back:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: ./back