name: main-workflow
on:
  push:
    branches:
      - front-dev
      - back-dev
      - feature/**
jobs:

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo build --verbose
      - run: echo "Build is done !"
