name: main-workflow
on:
  push:
    branches:
      - front-dev
      - back-dev
      - feature/**
jobs:

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Rustup update"
        run: rustup update

      - name: "Build cargo"
        run: cargo build --verbose
        working-directory: ./back

      - run: echo "Build is done !"

  check-code:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Chekcout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
